service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: ${{ secrets.AWS_REGION }}

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: dynamoPythonIncidentReporterDemo
    handler: lambda_function.lambda_handler
    description: dynamoPythonIncidentReporterDemo
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"